@startuml

participant "Data Management Board" as dmb
' participant Rocket ESP32 as resp
' participant Ground ESP32 as gesp
participant "Ground Systems Server" as gs

==PRELAUNCH==

dmb -> dmb : Boot into PreLaunch phase

loop While in PreLaunch
    gs -> dmb : Heartbeat
    dmb -> gs : Current tick "time"
else No heartbeat for 3 minutes
    dmb -> dmb : Abort
end

loop TX Sensor Data (100ms)
    dmb -> gs : Current sensor readings
end

group Log Initialization
    gs -> dmb : Clear log flash memory
    dmb -> dmb : Full-erase of external SPI flash
    note left
        Takes up to 4 minutes.
    end note
    dmb -> gs : Flash erased, ready to log flight
end
note right
    This can be done
    at any time during
    the PreLaunch phase,
    and is sent manually.
end note

==ARM==

gs -> dmb : Arm command
dmb -> dmb : Transition to Arm phase

loop While in PreLaunch
    gs -> dmb : Heartbeat
    dmb -> gs : Current tick "time"
else No heartbeat for 3 minutes
    dmb -> dmb : Abort
end

loop Slow Log (500ms)
    dmb -> dmb : Log sensor states
end

loop TX Sensor Data (100ms)
    dmb -> gs : Current sensor readings
end

==BURN==

gs -> dmb : Launch command
gs -> dmb : Launch command
gs -> dmb : Launch command
dmb -> dmb : Transition to Launch phase

loop Fast Log (100ms)
    dmb -> dmb : Log sensor states
end

loop TX Sensor Data (100ms)
    dmb -> gs : Current sensor readings
end

==COAST==

note over dmb, gs
    Automatically transitions after predetermined burn time (5.55s)
end note

dmb -> dmb : Transition to Burn phase

loop Fast Log (100ms)
    dmb -> dmb : Log sensor states
end

loop TX Sensor Data (100ms)
    dmb -> gs : Current sensor readings
end

==POSTFLIGHT==

note over dmb, gs
    Automatically transitions after 10 minutes,
    meaning the rocket is on the ground.
end note

loop Slow Log (500ms)
    dmb -> dmb : Log sensor states
    note right
        From here on out, the DMB will
        continue to log at this rate
        until the storage is full,
        or power is cut.
    end note
end

loop TX Sensor Data (500ms)
    dmb -> gs : Current sensor readings
    note right
        This is unlikely to reach the
        original GS location, but could
        aide in locating the rocket
        after it lands.
    end note
end

newpage

==ABORT_COMMANDRECEIVED==

gs -> dmb : Abort command

note over dmb
    Wait to be reset.
    This can be done remotely with a reset command.
end note

==ABORT_NOHEARTBEAT==

note over dmb
    No heartbeat received for 3 minutes.
end note

note over dmb
    Wait to be reset.
    This can be done remotely with a reset command.
end note

@enduml