addons:
    apt:
        packages:
            - libc6:i386
            - libncurses5:i386
            - libstdc++6:i386
before_install:
    - git clone https://github.com/StudentOrganisationForAerospaceResearch/DevelopmentResources.git
install:
    - (cd DevelopmentResources/STM32Resources && sudo ./install.sh)
    - rm DevelopmentResources -rf
    - wget 'https://s3-us-west-2.amazonaws.com/ucsolarteam.hostedfiles/astyle'
    - tar -zxvf astyle
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf

before_script:
    - source ~/.profile

script:
    - make
    - "! (astyle 'Inc/*.h' 'Src/*.c' -r --dry-run --options=astylerc | grep Formatted)"

language: c
